.github/codeowners
.github/workflows/assign_issue_to_project.yml
.github/workflows/dependent_items.yml
.github/workflows/license_check.yml
project/plugins.sbt

* Added license_check.yml
* Added dependent_items.yml
* Renamed assign_project_to_issue.yml to assign_issue_to_project.yml
* Added codeowners
Closes #56

#56: Add common project workflows

---

agent/src/main/scala/za/co/absa/atum/agent/AtumAgent.scala
agent/src/main/scala/za/co/absa/atum/agent/dispatcher/ConsoleDispatcher.scala
agent/src/main/scala/za/co/absa/atum/agent/dispatcher/Dispatcher.scala
agent/src/main/scala/za/co/absa/atum/agent/dispatcher/HttpDispatcher.scala
server/src/main/scala/za/co/absa/atum/server/api/controller/PrototypeController.scala

- also fix Future/CompletableFuture issue on server
fixes #122

#122 createPartitioning from client to server functionality

---

server/Dockerfile

Will need to retrigger the ECR push once this is merged. But not sure if this really is causing the problems.

wrong format of application.properties file

---

project/Dependencies.scala
server/src/main/resources/reference.conf
server/src/main/scala/za/co/absa/atum/server/Main.scala
server/src/main/scala/za/co/absa/atum/server/api/database/TransactorProvider.scala
server/src/main/scala/za/co/absa/atum/server/aws/AwsSecretsProvider.scala
server/src/main/scala/za/co/absa/atum/server/aws/AwsSecretsProviderImpl.scala
server/src/main/scala/za/co/absa/atum/server/config/AwsConfig.scala
server/src/test/scala/za/co/absa/atum/server/ConfigProviderSpec.scala
server/src/test/scala/za/co/absa/atum/server/api/database/runs/functions/CreatePartitioningIfNotExistsSpec.scala
server/src/test/scala/za/co/absa/atum/server/api/database/runs/functions/WriteCheckpointSpec.scala
server/src/test/scala/za/co/absa/atum/server/aws/AwsSecretsProviderSpec.scala

Reads credentials from AWS Secrets Manager. 
Closes #107

aws secrets provider

---

.github/workflows/build.yml
.github/workflows/release_publish.yml
project/Setup.scala

* removed incompatible settings from sbt project setup
* separated Sonatype and GitHub release, as they use different Java versions
* updated build.yml for newest action versions
Closes #205

#205: Release process is broken

---

server/src/test/scala/za/co/absa/atum/server/api/http/BaseEndpointsUnitTests.scala

#215: class name was ignored so were tests in some parts of CICD

---

.github/workflows/jacoco_report.yml

* added check on server coverage
* added optional check on overall coverage of modules
* rename of some variables
Closes #217

#217: JaCoCo Report workflow is not checking server module coverage

---

database/src/main/postgres/runs/V1.5.10__write_checkpoint.sql
database/src/main/postgres/runs/V1.9.2__write_checkpoint.sql
database/src/test/scala/za/co/absa/atum/database/runs/WriteCheckpointIntegrationTests.scala
database/src/test/scala/za/co/absa/atum/database/runs/WriteCheckpointOverloadedIntegrationTests.scala
server/src/main/scala/za/co/absa/atum/server/api/http/Endpoints.scala
server/src/test/scala/za/co/absa/atum/server/api/controller/CheckpointControllerUnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/database/runs/functions/WriteCheckpointIntegrationTests.scala
server/src/test/scala/za/co/absa/atum/server/api/database/runs/functions/WriteCheckpointV2IntegrationTests.scala
server/src/test/scala/za/co/absa/atum/server/api/http/PostCheckpointEndpointV2UnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/repository/CheckpointRepositoryUnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/service/CheckpointServiceUnitTests.scala

Fixes error/status codes for POST checkpoint operation
Closes #255

status code for partitioning not found

---

database/src/main/postgres/runs/V1.5.16__create_or_update_additional_data.sql
database/src/test/scala/za/co/absa/atum/database/runs/CreateOrUpdateAdditionalDataIntegrationTests.scala
model/src/main/scala/za/co/absa/atum/model/dto/AdditionalDataPatchDTO.scala
model/src/main/scala/za/co/absa/atum/model/dto/AdditionalDataPatchItemDTO.scala
server/src/main/scala/za/co/absa/atum/server/api/controller/BaseController.scala
server/src/main/scala/za/co/absa/atum/server/api/controller/PartitioningController.scala
server/src/main/scala/za/co/absa/atum/server/api/controller/PartitioningControllerImpl.scala
server/src/main/scala/za/co/absa/atum/server/api/database/runs/functions/CreateOrUpdateAdditionalData.scala
server/src/main/scala/za/co/absa/atum/server/api/http/Endpoints.scala
server/src/main/scala/za/co/absa/atum/server/api/http/Routes.scala
server/src/main/scala/za/co/absa/atum/server/api/repository/PartitioningRepository.scala
server/src/main/scala/za/co/absa/atum/server/api/repository/PartitioningRepositoryImpl.scala
server/src/main/scala/za/co/absa/atum/server/api/service/PartitioningService.scala
server/src/main/scala/za/co/absa/atum/server/api/service/PartitioningServiceImpl.scala
server/src/main/scala/za/co/absa/atum/server/model/AdditionalDataItemFromDB.scala
server/src/test/scala/za/co/absa/atum/server/api/TestData.scala
server/src/test/scala/za/co/absa/atum/server/api/controller/PartitioningControllerUnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/database/runs/functions/CreateOrUpdateAdditionalDataIntegrationTests.scala
server/src/test/scala/za/co/absa/atum/server/api/database/runs/functions/WriteCheckpointV2IntegrationTests.scala
server/src/test/scala/za/co/absa/atum/server/api/http/GetPartitioningAdditionalDataV2EndpointUnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/http/GetPartitioningCheckpointV2EndpointUnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/http/PatchAdditionalDataEndpointUnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/repository/PartitioningRepositoryUnitTests.scala
server/src/test/scala/za/co/absa/atum/server/api/service/PartitioningServiceUnitTests.scala

Introduces PATCH endpoint for additional data
Closes #221

patch additional data

---

agent/src/main/scala/za/co/absa/atum/agent/AtumContext.scala
agent/src/main/scala/za/co/absa/atum/agent/exception/AtumAgentException.scala
build.sbt

Fixes sub partitions context creation.
Fixes #261

PartitioningUpdateException

---

project/Setup.scala
server/README.md
server/src/main/resources/logback.xml
server/src/main/resources/reference.conf

Dockerfile and application configuration verified for upcoming deployment.
Closes #260

verify docker image

---

server/src/main/scala/za/co/absa/atum/server/api/http/Routes.scala

* This PR implement the functionality if hiding in-active endpoint from swagger documentation.
`Closes` #263

Hiding in-active endpoints: #263

---

.github/workflows/release_draft.yml

*  AbsaOSS/generate-release-notes downgraded to released version from a development branch
Eventually #285

#285: Atum Release 0.3.0 - script downgrade

---

server/Dockerfile

Closes #292 
Related to https://github.com/absa-group/atum-service-deployment/pull/40/files

#292: the docker_entrypoint.sh file might not be found if the docker build runs from another directory

---

project/Dependencies.scala

aws sts dependency

---

.github/workflows/release-notes-presence-check.yml
.github/workflows/release_draft.yml

Release Notes:
- Updated workflow for release notes presence in PR body.
- Updated workflow for release draft creation.
Closes #308

#308 - Update of Release Notes generator and check workflows

---

.github/workflows/jacoco_report.yml
build.sbt

* reader is to be published
Closes #254 
Release notes:
* **Reader** library is now part of the release.

#254: Set the Reader module for publishing

---

agent/src/main/scala/za/co/absa/atum/agent/model/Measure.scala
agent/src/main/scala/za/co/absa/atum/agent/model/MeasuresBuilder.scala
agent/src/test/scala/za/co/absa/atum/agent/model/AtumMeasureUnitTests.scala
agent/src/test/scala/za/co/absa/atum/agent/model/MeasureUnitTests.scala
agent/src/test/scala/za/co/absa/atum/agent/model/MeasuresBuilderUnitTests.scala

-Add support for sum of truncated values.
-Added the `aggregatedTruncTotal` and `absAggregatedTruncTotal` Measures.
Closes #314 
Release notes:
-Added the `aggregatedTruncTotal` and `absAggregatedTruncTotal` Measures.
-Added the tests for these Measures.

#314: Add support for sum of truncated values 

---

reader/src/main/scala/za/co/absa/atum/reader/FlowReader.scala
reader/src/main/scala/za/co/absa/atum/reader/PartitioningReader.scala
reader/src/main/scala/za/co/absa/atum/reader/core/Reader.scala
reader/src/test/scala/za/co/absa/atum/reader/FlowReaderUnitTests.scala

MonadError instance passed as implicit evidence instead of type bound.
Closes #339 
Release notes:
- Reader classes' signatures changed to receive MonadError instance as implicit evidence instead of type bound

monad error as implicit evidence instead of type bound in reader classes

---

api-tests/1_shot/Atum-Service_1-Shot_test_flow.postman_collection.json
project/plugins.sbt
server/src/test/scala/za/co/absa/atum/server/api/v2/controller/PartitioningControllerUnitTests.scala

This is a continuation of this ticket: #361 that covered 100% of REST API endpoints. This contains the partitioning ancestor REST API endpoints.
Closes #367
Release Notes:
- `getPartitioningAncestors` REST API endpoint test
- `patchPartitioningParents` REST API endpoint test
- `health/readiness` REST API endpoint test
- `health/liveness` REST API endpoint test

#367-REST-API-test-coverage-ancestor-functionality
